### ISSUE TITLE
Build Failure: Text must not be null or empty 

### ISSUE THREAD

**Issue by PestusAtSAG** [SoftwareAG/cumulocity-microservice-archetype#16]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.471 s
[INFO] Finished at: 2023-12-13T18:02:05+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project standalone-pom: Text must not be null or empty → [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] [MojoFailureException - Apache Maven - Apache Software Foundation](http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException)

**Comment by ButKor** [comment]
Might or might not be helpful: Had the same problem at one point. The first build fails with above error. It created the Service in Cumulocity though. When running the same build a second time, the build succeeds. It looked to me as if the maven build would a Microservice in Cumulocity upfront in order to succeed.

**Comment by PestusAtSAG** [comment]
The problem is in the groovy script which registers the microservice at the platform is somehow failing. Actually this functionality is the one of the big value proposition of this archetype. So this should work. I will investiage further and add more log output to the goovy script to understand why it is failing!
